#pragma once


namespace pandemic{
	// Defines a direction of a message on the board
	enum class City {
		Algiers,
        Atlanta,
        Bogota,
        BuenosAires,
        Baghdad,
        Bangkok,
        Beijing,
        Cairo,
        Chennai,
        Chicago,
        Delhi,
        Essen,
        HongKong,
        Istanbul,
        Jakarta,
        Kinshasa,
        Kolkata,
        Lagos,
        London,
		MexicoCity,
        Manila,
        Miami,
        Montreal,
        Moscow,
        Mumbai,
        NewYork,
        Osaka,
        Paris,
        Riyadh,
        SanFrancisco,
        Santiago,
        Shanghai,
        Sydney,
        Taipei,
        Tehran,
        Tokyo,
        StPetersburg,
        HoChiMinhCity,
        Johannesburg,
        Karachi, 
        Khartoum,
        SaoPaulo,
        Washington,
        Madrid,
        Seoul,
        LosAngeles,
        Milan,
        Lima
	};
}

